### ISSUE TITLE
What problem does this fix?  My ender-3 temp seems fine.

### ISSUE THREAD

**Issue by mark-hahn** [SimplyPrint/OctoPrint-Ender3V2TempFix#1]

**Comment by cp2004** [comment]
Details of the two problems associated with creality printers are documented here:
https://community.octoprint.org/t/octoprint-doesnt-show-a-temperature-graph-for-my-creality-printer/23901

Maybe you got firmware before it was messed up, or they fixed it.

**Comment by mark-hahn** [comment]
Ah.  The first think I did when I got my ender-3 was replace the firmware.  Thanks.
