### ISSUE TITLE
Still reporting double temp data

### ISSUE THREAD

**Issue by Etb1025** [SimplyPrint/OctoPrint-Ender3V2TempFix#17]
I am very new to all of this, so sorry if this is silly and annoying.

I have an ender 3 pro. Adding octopi now and got the notificaiton that my printer shipped with firmware that prodices the 2x temp data. I used the .zip on the github page and installed from the plugin manager. But, the terminal is still reporting doubled readings. I am not sue what i did wrong.

**Comment by AlbertMN** [comment]
It's fixed, just still shows the wrong temperature in the Terminal :)

> Just to clarify to anyone else reading this; the plugin works, and does what it's supposed to do, but as the "terminal" tab shows the raw content it gets from the printer, it still look weird in the GCODE terminal, also resulting in the "suppress temperature" feature not working.
> 
> I had not thought of the suppress feature, so I'll see what I can do about that :)



https://github.com/SimplyPrint/OctoPrint-Creality2xTemperatureReportingFix/issues/10#issuecomment-716045501
