### ISSUE TITLE
No problem with Ender 3 Max and 4.2.2 Mainboard

### ISSUE THREAD

**Issue by mkurrein** [SimplyPrint/OctoPrint-Ender3V2TempFix#19]
I’ve just set up Octoprint on my Pi connecting to my new Ender 3 Max.  This has the 4.2.2 motherboard and firmware with CR Touch is V1.0.1.6.
It’s all displaying as it should, including temperature.
How do I disable the warning about Broken Firmware, please?
![Image 01-01-2022 at 15 17](https://user-images.githubusercontent.com/96948522/147853891-64f92829-e861-4d61-b8d4-d7a19b21bedb.jpg)

**Comment by AlbertMN** [comment]
The warning isn't casued by this plugin, but by the "Firmware-Check" plugin by Gina (@foosel).

Please try and check under the "Terminal" tab to see if the temperatures are reported in the correct format _(an attached screenshot would be nice)_, so we can see whether it's a false positive.

**Comment by mkurrein** [comment]
Thanks, will do!

**Comment by mkurrein** [comment]
Hi

My apologies, this was my error.

I have now installed the @x plug in an the warning has gone and the temperture is being sent correctly.

I will delete my post.

Thanks again

Martin

**Comment by AlbertMN** [comment]
All good - just leave it up, others might have the same question :) closing the issue.
