### ISSUE TITLE
Please describe the issue in the Readme

### ISSUE THREAD

**Issue by profucius** [SimplyPrint/OctoPrint-Ender3V2TempFix#2]
I found this plugin in the OctoPrint new plugins list, and have an Ender printer, but I am unsure what the issue is that this plugin serves to resolve. Please add a brief description of the issue to your Readme, so that people who find your plugin in the future will know if they need to install it or not.

**Comment by AlbertMN** [comment]
The readme has been updated here on GitHub. Will update the plugin repository later :)
